# Generated by Django 5.2 on 2025-04-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='repcontraseña',
        ),
    ]
